Fix testing options
* Makefile.am: Add wget2 executable from builddir
* contrib/check_options: Use given command line arguments

diff --git a/contrib/check_options b/contrib/check_options
--- a/contrib/check_options
+++ b/contrib/check_options
@@ -2,20 +2,30 @@
 
 shopt -s extglob # enable pattern matching for 'case'
 
+DOCFILE=docs/wget2.md
+if [ -n "$1" ]; then
+  DOCFILE="$1"
+fi
+
+WGET2=src/wget2
+if [ -n "$2" ]; then
+  WGET2="$2"
+fi
+
 err=0
 
 # won't process these options
 excludes="+(--no-quiet|--html-extension)"
 
-for opt in `src/wget2 --help|egrep -o -- '--[a-zA-Z0-9-]+'|sort -u`; do
+for opt in `$WGET2 --help|egrep -o -- '--[a-zA-Z0-9-]+'|sort -u`; do
   # skip if in $excludes
   case $opt in $excludes) continue;; esac
 
-  if ! egrep -q -- " \`$opt(=|\`|\[)" $1; then
+  if ! egrep -q -- " \`$opt(=|\`|\[)" $DOCFILE; then
     # search for the --no- variant
     noopt="--no-`echo $opt|cut -c3-`"
-    if ! egrep -q -- " \`$noopt\`" $1; then
-      echo "Failed to find \`$opt in $1"
+    if ! egrep -q -- " \`$noopt\`" $DOCFILE; then
+      echo "Failed to find \`$opt in $DOCFILE"
       err=1
     fi
   fi
